<?php
/**
 * Plugin Name:       Custom WPBakery Elements (Site Library)
 * Description:       This site's own custom WPBakery elements. Definitions live in this plugin's elements/ folder as JSON. Fully standalone — elements keep working and stay editable even if the authoring plugin (MCP WPBakery Bridge) is removed.
 * Version:           1.0.0
 * Requires PHP:      7.2
 * License:           GPL-2.0-or-later
 *
 * Generated by MCP WPBakery Bridge. Safe to keep forever; safe to edit the
 * JSON files by hand. Each element is registered as a NATIVE, editable
 * WPBakery element (every field is a vc_map param) and rendered from its
 * HTML template with escaped values, so the theme never re-parses it.
 *
 * Template syntax (per element JSON "template"):
 *   {{param}}              value, escaped per the param's "escape" (text|html|url)
 *   {{{param}}}            value through wp_kses_post (rich HTML fields)
 *   {{#if param}}...{{/if}}      render only when the value is non-empty
 *   {{#each group}}...{{/each}}  loop a param_group; inside, {{field}} is the row field
 *   {{content}}            inner content (enclosing elements), shortcodes expanded
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( class_exists( 'Custom_WPB_Elements_Library' ) ) {
	return;
}

class Custom_WPB_Elements_Library {

	const LOADER_VERSION = '1.0.0';

	/** @var array<string,array>|null */
	private $elements = null;

	/** @var array<string,bool> */
	private $css_printed = array();

	public static function boot() {
		$lib = new self();
		add_action( 'init', array( $lib, 'register_shortcodes' ), 5 );
		add_action( 'vc_before_init', array( $lib, 'map_elements' ) );
	}

	private function elements_dir() {
		return plugin_dir_path( __FILE__ ) . 'elements/';
	}

	/** @return array<string,array> tag => definition */
	private function elements() {
		if ( null !== $this->elements ) {
			return $this->elements;
		}
		$this->elements = array();
		foreach ( (array) glob( $this->elements_dir() . '*.json' ) as $file ) {
			$def = json_decode( (string) file_get_contents( $file ), true );
			if ( is_array( $def ) && ! empty( $def['tag'] ) && preg_match( '/^[a-z][a-z0-9_]*$/', $def['tag'] ) ) {
				$this->elements[ $def['tag'] ] = $def;
			}
		}
		return $this->elements;
	}

	public function register_shortcodes() {
		$lib = $this;
		foreach ( $this->elements() as $tag => $def ) {
			add_shortcode(
				$tag,
				function ( $atts, $content = '' ) use ( $lib, $tag ) {
					return $lib->render( $tag, is_array( $atts ) ? $atts : array(), (string) $content );
				}
			);
		}
	}

	public function map_elements() {
		if ( ! function_exists( 'vc_map' ) ) {
			return;
		}
		foreach ( $this->elements() as $tag => $def ) {
			$params = array();
			foreach ( (array) ( isset( $def['params'] ) ? $def['params'] : array() ) as $p ) {
				if ( is_array( $p ) && ! empty( $p['param_name'] ) && ! empty( $p['type'] ) ) {
					unset( $p['escape'] ); // library-only key; not part of vc_map
					$params[] = $p;
				}
			}
			vc_map(
				array(
					'name'        => isset( $def['name'] ) ? $def['name'] : $tag,
					'base'        => $tag,
					'category'    => isset( $def['category'] ) ? $def['category'] : 'Custom Elements',
					'description' => isset( $def['description'] ) ? $def['description'] : '',
					'icon'        => 'icon-wpb-ui-custom_heading',
					'params'      => $params,
				)
			);
		}
	}

	public function render( $tag, $atts, $content ) {
		$all = $this->elements();
		if ( empty( $all[ $tag ] ) ) {
			return '';
		}
		$def      = $all[ $tag ];
		$defaults = array();
		$defs     = array();
		foreach ( (array) ( isset( $def['params'] ) ? $def['params'] : array() ) as $p ) {
			if ( ! is_array( $p ) || empty( $p['param_name'] ) || 'content' === $p['param_name'] ) {
				continue;
			}
			$defaults[ $p['param_name'] ] = isset( $p['std'] ) && is_scalar( $p['std'] ) ? (string) $p['std'] : '';
			$defs[ $p['param_name'] ]     = $p;
		}
		$values = shortcode_atts( $defaults, $atts );

		$html = $this->render_scope(
			(string) ( isset( $def['template'] ) ? $def['template'] : '' ),
			$values,
			$defs,
			$content
		);

		$css = (string) ( isset( $def['css'] ) ? $def['css'] : '' );
		if ( '' !== $css && empty( $this->css_printed[ $tag ] ) ) {
			$this->css_printed[ $tag ] = true;
			$html = '<style id="cwpb-' . esc_attr( $tag ) . '">' . $css . '</style>' . $html;
		}
		return $html;
	}

	/* ------------------------------------------------------------------ */
	/* Mini template engine                                                 */
	/* ------------------------------------------------------------------ */

	private function render_scope( $tpl, $values, $defs, $content = null ) {
		$lib = $this;

		// {{#each group}}...{{/each}} — loop param_group rows.
		$tpl = preg_replace_callback(
			'/\{\{#each ([a-z0-9_]+)\}\}(.*?)\{\{\/each\}\}/s',
			function ( $m ) use ( $lib, $values, $defs ) {
				$rows      = $lib->group_rows( isset( $values[ $m[1] ] ) ? $values[ $m[1] ] : '' );
				$row_defs  = array();
				if ( isset( $defs[ $m[1] ]['params'] ) && is_array( $defs[ $m[1] ]['params'] ) ) {
					foreach ( $defs[ $m[1] ]['params'] as $p ) {
						if ( is_array( $p ) && ! empty( $p['param_name'] ) ) {
							$row_defs[ $p['param_name'] ] = $p;
						}
					}
				}
				$out = '';
				foreach ( $rows as $row ) {
					$out .= $lib->render_scope( $m[2], is_array( $row ) ? $row : array(), $row_defs );
				}
				return $out;
			},
			(string) $tpl
		);

		// {{#if param}}...{{/if}} — keep only when non-empty.
		$tpl = preg_replace_callback(
			'/\{\{#if ([a-z0-9_]+)\}\}(.*?)\{\{\/if\}\}/s',
			function ( $m ) use ( $values ) {
				$v = isset( $values[ $m[1] ] ) ? trim( (string) $values[ $m[1] ] ) : '';
				return '' !== $v ? $m[2] : '';
			},
			$tpl
		);

		// {{content}} — inner content of enclosing elements.
		if ( null !== $content ) {
			$tpl = str_replace( '{{content}}', do_shortcode( $content ), $tpl );
		}

		// {{{param}}} — rich HTML through kses.
		$tpl = preg_replace_callback(
			'/\{\{\{([a-z0-9_]+)\}\}\}/',
			function ( $m ) use ( $values ) {
				return wp_kses_post( (string) ( isset( $values[ $m[1] ] ) ? $values[ $m[1] ] : '' ) );
			},
			$tpl
		);

		// {{param}} — escaped per the param's declared escape.
		return preg_replace_callback(
			'/\{\{([a-z0-9_]+)\}\}/',
			function ( $m ) use ( $values, $defs ) {
				$v = (string) ( isset( $values[ $m[1] ] ) ? $values[ $m[1] ] : '' );
				$escape = isset( $defs[ $m[1] ]['escape'] ) ? $defs[ $m[1] ]['escape'] : 'text';
				if ( 'url' === $escape ) {
					return esc_url( $v );
				}
				if ( 'html' === $escape ) {
					return wp_kses_post( $v );
				}
				return esc_html( $v );
			},
			$tpl
		);
	}

	/** Decode a param_group value into a list of assoc rows. */
	public function group_rows( $value ) {
		if ( empty( $value ) ) {
			return array();
		}
		if ( function_exists( 'vc_param_group_parse_atts' ) ) {
			return (array) vc_param_group_parse_atts( $value );
		}
		$decoded = json_decode( rawurldecode( (string) $value ), true );
		return is_array( $decoded ) ? $decoded : array();
	}
}

Custom_WPB_Elements_Library::boot();
